// Root build file for qap-junit-5-plugin multi-module project
// All code has been moved to sub-modules

allprojects {
    group = 'com.mk.fx.qa'
    version = '1.1.0-SNAPSHOT'
}

subprojects {
    apply plugin: 'java'
    
    repositories {
        mavenCentral()
    }
    
    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}
